### PR TITLE
Improve safe queue

### PR DESCRIPTION
**Pull request by benvenutti**
Summary of improvements on `SafeQueue`:

1. const correctness
2. move semantics (now with `emplace`)
4. `pop()` now returns a `std::optional` that will be `std::nullopt` if the queue is empty

@pirovc, do profile these changes **thoroughly** before merging. Please, keep in mind this was done without a way to profile the results of the changes. **It should not make it worse**... but who knows for sure? Keep me updated on the results. Maybe we can tweak this a bit more!

### CODE REVIEW

**Comment by benvenutti** [comment]
Let park this PR for now and wait for #29 to be merged.

**Comment by benvenutti** [comment]
Hey @pirovc , the PR is finally updated. With the unit tests, it was easy to spot the issue. The problem was just a misuse of the safe queue's new public interface. At one point the returned value was being used without validation. This was **not an issue before because the queue would return a default value, that is yet valid.**

**Comment by pirovc** [comment]
Thank you @benvenutti 
I tested the PR and noticed a slow-down of aroun 5% on the ganon-classify with the new queue. Since this project is very performance-dependent I will have to hold this PR now. I will try to re-factor the queue with some of your improvments and see where the speed issues are coming from.

**Comment by benvenutti** [comment]
Hey @pirovc , sure, let's park this PR until we find out what's the issue with it

**Comment by pirovc** [comment]
Declined it is! Thanks

**Pull request closed without merging**
